version: '1'
services:
app1:
build: ./backend1
ports:
- "5001:5000"
app2:
build: ./backend2
ports:
- "5002:5000"
nginx:
build: ./nginx
ports:
- "8080:80"
depends_on:
- backend1
- backend2